### ISSUE TITLE
pnpm run error Package subpath './src' is not defined by "exports"

### ISSUE THREAD

**Issue by tong233** [Dunqing/vite-ant-design-pro#1]
大佬项目很赞
pnpm create ant-design-pro@latest 按装跑起来报错
yarn 没问题
```
Package subpath './src' is not defined by "exports" in /Users/xxx/Documents/github/vite-antd-pro/node_modules/.pnpm/vite-plugin-antd-layout@0.2.2_x4ypkww7sjudj6ohf2dzwm6xhq/node_modules/ant-design-pro-layout/package.json
```

另外动态主题颜色没换完全，menu文字和checkbox

**Comment by Dunqing** [comment]
谢谢！我空了修复下

**Comment by Dunqing** [comment]
> pnpm create ant-design-pro@latest 按装跑起来报错 yarn 没问题
> 
> ```
> Package subpath './src' is not defined by "exports" in /Users/xxx/Documents/github/vite-antd-pro/node_modules/.pnpm/vite-plugin-antd-layout@0.2.2_x4ypkww7sjudj6ohf2dzwm6xhq/node_modules/ant-design-pro-layout/package.json
> ```
> 

我测了下这个，没有问题。
pnpm: 7
node: 16

方便的话可以提供个复现的repo

**Comment by Dunqing** [comment]
> > pnpm create ant-design-pro@latest 按装跑起来报错 yarn 没问题
> > ```
> > Package subpath './src' is not defined by "exports" in /Users/xxx/Documents/github/vite-antd-pro/node_modules/.pnpm/vite-plugin-antd-layout@0.2.2_x4ypkww7sjudj6ohf2dzwm6xhq/node_modules/ant-design-pro-layout/package.json
> > ```
> 
> 我测了下这个，没有问题。 pnpm: 7 node: 16
> 
> 方便的话可以提供个复现的repo


跑起来后 复现了
